name: Automated Changelog PR

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for changelog generation
      - uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md
          skip-version-file: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update CHANGELOG.md"
          title: "chore: update CHANGELOG.md"
          body: |
            This PR updates the changelog automatically based on recent commits.
            Please review and merge.
          branch: "changelog/update"
