name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - chore/test_alignment # Explicitly add your branch here to ensure it triggers
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest mypy
          pip install -r requirements.txt

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Run Ruff (Linting & Formatting)
        run: |
          ruff check . --config pyproject.toml
          ruff format . --check --config pyproject.toml

      - name: Run Pytest (Tests)
        run: pytest

      - name: Run MyPy (Type Checking)
        run: mypy .

      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov/
        if: always()